### ISSUE TITLE
Failing on jshint

### ISSUE THREAD

**Issue by ratracegrad** [s-yadav/angulargrid#1]
We use jshint as part of our grunt build process to verify best practices in coding. Your angulargrid generates 17 errors. Do you have a version that will pass jshint?

**Comment by s-yadav** [comment]
Hi ratracegrad,
Thanks for reporting it, I have committed a new build with jshint warning fixes. Please check that out, 
If still you are getting warnings just post me those warning.

**Comment by ratracegrad** [comment]
Hello,

Thanks for the update. I am still getting 7 errors with jshint.

client\components\angulargrid\angulargrid.js
  line 12   col 5   Missing "use strict" statement.
  line 28   col 72  Strings must use singlequote.
  line 62   col 76  Strings must use singlequote.
  line 62   col 68  Expected '===' and instead saw '=='.
  line 172  col 49  Expected '{' and instead saw 'return'.
  line 234  col 45  Expected '{' and instead saw '$timeout'.
  line 242  col 31  Expected '{' and instead saw 'angularGridInstance'.

**Comment by s-yadav** [comment]
I have committed a new build. Warning 4 need to be in == , so you have to ignore it, 
Though updated warning 5,6,7, it also can be ignored as those are single line if statement.

**Comment by ratracegrad** [comment]
Thanks!
