### ISSUE TITLE
Grid refresh on select

### ISSUE THREAD

**Issue by alereisan** [s-yadav/angulargrid#17]
I love your Grid so far, but now I need to implement multiple sortBy Filters which happen on select:

```
<md-input-container>
  <label>Order by...</label>
  <md-select ng-model="sortBy">
    <md-option ng-repeat="option in options" value="{{option}}">
      {{option}}
    </md-option>
  </md-select>
</md-input-container>
```

in the controller i just have:
```
  $scope.options = ['product', 'condition', '-created_at']; //all sortBy options
  $scope.sortBy = '-created_at'; //default sortBy Value
```

the selected option updates the sortBy model and should then automatically update the grid:
```
<ul hide-sm class="dynamic-grid" angular-grid="images" grid-width="200" gutter-size="10" angular-grid-id="image-feed" refresh-on-img-load="true">
  <li ng-repeat="image in images | orderBy:sortBy" class="grid">
    {{image.product}} - {{image.condition}} - {{image.created_at}}
  </li>
</ul>
```

It works perfectly if i put ```angular-grid="sortBy"```. is there a simple way to use ```angular-grid=""``` to listen to multiple models?

I don't understand how to implement the manual refresh stated in the documentation, could you please provide an example for a "select" scenario?

Thank you.

**Comment by s-yadav** [comment]
Here is sample snippet you can use for your case

```js

App.controller('YourCtrl',['$scope','angularGridInstance',function($scope,angularGridInstance){

.....
.....

$scope.$watch('sortBy',function(){
   angularGridInstance['image-feed'].refresh();
});

}])

```

I am planning for a rewrite of few parts of the plugin, hope that will make this cases simpler.

**Comment by alereisan** [comment]
Thanks for the reply, but when I do this, I get this error:

```
TypeError: Array.prototype.slice called on null or undefined
    at domToAry (angulargrid-a85aab5ef32db238e32e7c307aaa7a80.js?body=1:35)
    at Object.reflowGrids [as refresh] (angulargrid-a85aab5ef32db238e32e7c307aaa7a80.js?body=1:132)
    at Object.fn (auctionCtrl-9eec40981af540ba82da72b1af435515.js?body=1:18)
    at Scope.$digest (angular-81b9b668c3f93c8ccb76b27ad984d9b6.js?body=1:15827)
    at Scope.$apply (angular-81b9b668c3f93c8ccb76b27ad984d9b6.js?body=1:16098)
    at done (angular-81b9b668c3f93c8ccb76b27ad984d9b6.js?body=1:10547)
    at completeRequest (angular-81b9b668c3f93c8ccb76b27ad984d9b6.js?body=1:10745)
    at XMLHttpRequest.requestLoaded (angular-81b9b668c3f93c8ccb76b27ad984d9b6.js?body=1:10686)
```

**Comment by s-yadav** [comment]
Particular error is fixed on latest commit. Let me know if it still give the same issue.

**Comment by alereisan** [comment]
Unfortunately still the same TypeError, I have updated to the master branch.

**Comment by s-yadav** [comment]
Have made some change, that must fix your issue. However this is a temporary fix, will be looking for the better approach for this use case.

**Comment by alereisan** [comment]
Thank you, this error is now gone. 

But there is still another issue, when using my sortBy select filter (which i described in the first post above). I have set the ```angular-grid-id="feed"``` within the ul, and am using the watch function in the controller:

```
  // makes feed watch sortBy filter
  $scope.$watch('sortBy', function(){
    angularGridInstance.feed.refresh();
  });
```

when I change my sortBy select value (choose another filter) nothing happens in the feed, but when I do something within the feed, like clicking on the like-button of a specific grid-item, it updates and reorders the feed by the value of the sortBy. Do you know what I am missing here?

**Comment by s-yadav** [comment]
Can you provide a js-fiddle / link, so I can check where exact problem is ?

**Comment by alereisan** [comment]
Problem was that I defined same angular-grid-id on 2 different grids.
